export const LOADED_FROM_DB = 'LOADED_FROM_DB';
export const DELETE_TASK_FROM_DB = 'DELETE_TASK_FROM_DB';
export const UPDATE_USER_TO_EDIT = 'UPDATE_USER_TO_EDIT';
export const UPDATE_TASKS_FOR_ONE_USER_DB = 'UPDATE_TASKS_FOR_ONE_USER_DB';